#Configs for custom_logger.py module. Outputs can be directed to any of the 
#handlers which is given as console, debug_file, and info_file. Every handler
#has its own log level. New handlers can be created, available ones can be modified. 

version: 1.0
disable_existing_loggers: False
formatters: 
    detailed:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s.py - Line %(lineno)s: %(message)s'
        datefmt: '%d-%b-%y %H:%M:%S'
    simple:
        format: '%(asctime)s - %(levelname)s - %(message)s'
        datefmt: '%d-%b-%y %H:%M:%S'
handlers:
    console:
        class: logging.StreamHandler
        level: ERROR
        formatter: simple
        stream: ext://sys.stdout
    debug_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: detailed
        filename: debug_logs.log
        maxBytes: 10485760 #10MB
        mode: a
        encoding: utf-8
    info_file:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: detailed
        filename: info_logs.log
        maxBytes: 10485760 #10MB
        mode: a
        encoding: utf-8
root:
    level: DEBUG
    handlers: [console, debug_file]
    
